language: elixir

elixir: "1.10.4"
otp_release: "22.3.4"

jobs:
  include:
    - elixir: "1.5.3"
      otp_release: "20.3.8"
    - elixir: "1.6.6"
      otp_release: "20.3.8"
    - elixir: "1.7.4"
      otp_release: "22.3.4"
    - elixir: "1.8.2"
      otp_release: "22.3.4"
    - elixir: "1.9.4"
      otp_release: "22.3.4"

services:
  - docker

before_install:
  - rm mix.lock
  - docker pull lphoward/fake-s3
  - docker run -d -p 4569:4569 lphoward/fake-s3
  - docker ps -a

env:
  - MIX_ENV=test

script:
  - mix compile --force --warnings-as-errors
  - mix format --check-formatted
  - mix coveralls.travis
