language: elixir

elixir:
  - '1.6.0'

services:
  - docker

before_install:
  - docker pull lphoward/fake-s3
  - docker run -d -p 4569:4569 lphoward/fake-s3
  - docker ps -a

env:
  - MIX_ENV=test

script:
  - mix coveralls.travis
