name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.3.4
          elixir-version: 1.10.4

      - name: Dependencies
        run: mix deps.get

      - name: Set version
        run: |
          perl -pi -e "s/version: \"0.0.0\"/version: \"${GITHUB_REF:11}\"/" mix.exs

      - name: Publish
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_TOKEN }}
